---
# Install and configure MailHog.
- hosts: deploy-vm-2

  tasks:

  - name: install go get
    shell : "apt-get -y install golang-go "
    become: yes
    become_user: root



  - name: get MailHog
    shell : "go install github.com/mailhog/MailHog@latest"

  
  - name: install mhsendemail
    shell : "go install github.com/mailhog/mhsendmail@latest"

  
  - name: copy mailhog service file
    template:
        src: ../files/mailhog/mailhog.service
        dest: "/etc/systemd/system/mailhog.service"
    become: yes
    become_user: root
    

  
  - name: ensure mailhog service started
    service:
        name: mailhog
        state: started
        enabled: yes
    become: yes


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      become: yes


    