---
# Install and configure MailHog.
- hosts: testapp

  tasks:

  - name: install go get
    shell : "sudo su && apt-get -y install golang-go "



  - name: get MailHog
    shell : "go get github.com/mailhog/MailHog"