---
# Install and configure MailHog.
- hosts: deploy-vm-2

  tasks:

  - name: install go get
    shell : "apt-get -y install golang-go "
    become: yes
    become_user: root



  - name: get MailHog
    shell : "go install github.com/mailhog/MailHog@latest"

  
  - name: install mhsendemail
    shell : "go install github.com/mailhog/mhsendmail@latest"

  - name: env path mhsendemail
    shell : "/usr/sbin/sendmail -S mail:1025"
  


    