---
# Install and configure MailHog.
- hosts: testapp

  tasks:

  - name: install go get
    shell : "apt-get -y install golang-go "
    become: yes
    become_user: root



  - name: get MailHog
    shell : "go install github.com/mailhog/MailHog@latest"

  
  - name: install mhsendemail
    shell : "go install github.com/mailhog/mhsendmail"

  - name: env path mhsendemail
    shell : "sendmail_path = /usr/local/bin/mhsendmail"
  


    